# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72698d48c04563fc5ea4ca952c32d208dd15aaaee8e8e6ffc43c87b57ca4b7a4984c5a363a1d731429c4c5c7e877da81a464dabaf84c954f16e939eee6d6b3f4

test:
  secret_key_base: 49247c4d040f905847572346fc62d6fa4bf407b81806bb5b24421fab3dc7cf46bee6727990341366cdb58a3d23445e13732255d759419406610cad63a1958c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
